### ISSUE TITLE
Respring after pressing tweak button on FLEX, selector not recognised 

### ISSUE THREAD

**Issue by Inc0n** [NSExceptional/Swizzle#1]
Error after looking at CrashReporter:

`-[UIResponder doesNotRecognizeSelector]`

from 
`-[FLEXManager _toggleSwizzleMenu] + 0x80`

EDIT:
after some investigation this selector is not recognised
`-[FLEXExplorerViewController toggleToolWithViewControllerProvider]`
I installed the flex from flex-noacti, which is a different flex than what swizzle intended to depends on

**Comment by Inc0n** [comment]
Solved, the default FLEX does not have this api. Need to use this version 

> https://github.com/NSExceptional/FLEX.git

**Comment by Inc0n** [comment]
works like a charm

**Comment by NSExceptional** [comment]
Yeah, it relies on the FLEXing tweak. Need to use my specific branch of FLEX to build it. Does my readme not reflect this? I might need to add a note about that
